### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by plutoyty** [go-zookeeper/zk#114]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8dc9cc]

goroutine 16 [running]:
github.com/go-zookeeper/zk.(*Conn).connect(0xc000506180)
        /root/go/pkg/mod/github.com/go-zookeeper/zk@v1.0.3/conn.go:392 +0x30c
github.com/go-zookeeper/zk.(*Conn).loop(0xc000506180, {0xe2a5a8?, 0x13ceea0})
        /root/go/pkg/mod/github.com/go-zookeeper/zk@v1.0.3/conn.go:428 +0x3c
github.com/go-zookeeper/zk.Connect.func1()
        /root/go/pkg/mod/github.com/go-zookeeper/zk@v1.0.3/conn.go:224 +0x25
created by github.com/go-zookeeper/zk.Connect in goroutine 1
        /root/go/pkg/mod/github.com/go-zookeeper/zk@v1.0.3/conn.go:223 +0x3d7
FAIL    command-line-arguments  0.039s
FAIL

**Comment by jeffbean** [comment]
closing dup of https://github.com/go-zookeeper/zk/issues/115
