### ISSUE TITLE
Question: Equivalent method for rmr

### ISSUE THREAD

**Issue by bzon** [go-zookeeper/zk#41]
Hello, I use rmr to delete a node using zkCli. What would be the equivalent Method for this?

I tried using `conn.Delete` but I'm not sure what is the version to pass.

```golang
conn.Delete(path, version)
```

**Comment by yonasstephen** [comment]
alternative is to get the node first to know the version
```
_, stat, _ := conn.Get(path)
conn.Delete(path, stat.Version)
```

**Comment by nemith** [comment]
A version of -1 will delete the latest version.  

Better documentation is needed here #4
