### ISSUE TITLE
Connection request from old client /172.20.0.1:42922; will be dropped if server is in r-o mode

### ISSUE THREAD

**Issue by domgolonka** [go-zookeeper/zk#42]
Not working with ZK version 3.4.9.

**Comment by nemith** [comment]
Can you provide steps to reproduce this issue?

**Comment by nemith** [comment]
@domgolonka  Can you provide more information on this issue?  (What exactly the issue is, how to recreate it, etc?)

**Comment by nemith** [comment]
Closing due to lack of information.
