### ISSUE TITLE
GSSAPI SASL authentication

### ISSUE THREAD

**Issue by microeastcowboy** [go-zookeeper/zk#46]
any plan support for gssapi sasl auth ? when zk with kerberos security enabled

**Comment by nemith** [comment]
No plans, but this could be added.  If this is a use case a PR would be welcomed.  A proposal on how this would be implemented would be useful so that we could have a pluggable authentication system.

**Comment by nemith** [comment]
Enough overlap with #40  to mark this as a dup for now.
