### ISSUE TITLE
How about add `context` feature

### ISSUE THREAD

**Issue by Mrliu8023** [go-zookeeper/zk#48]

**Comment by pmazzini** [comment]
This is similar to https://github.com/go-zookeeper/zk/issues/12

**Comment by nemith** [comment]
Is cancellation your main use case for context or something else?

**Comment by Mrliu8023** [comment]
> Is cancellation your main use case for context or something else?

OCD obsessive-compulsive disorder

**Comment by nemith** [comment]
OCD is not a good reason to do something :)  Closing as duplicate of #12
