### ISSUE TITLE
Method `ChildrenW` only returns EventNodeChildrenChanged?

### ISSUE THREAD

**Issue by thep0y** [go-zookeeper/zk#56]
The `ChildrenW` method can only watch the changes of the children, but not the specific changes that occur in the children, such as `delete`, `create`, or `set`?
Or is there something wrong with my code?

```go

rootPath := "/root"

for {
		_, _, eventChannel, err := conn.ChildrenW(rootPath)
		if err != nil {
			panic(err)
		}

		e := <-eventChannel
		if e.Err != nil {
			panic(e.Err)
		}

		if e.Type == zk.EventNodeCreated {
			fmt.Printf("child node[%s] has beed deteted\n", e.Path)
		} else if e.Type == zk.EventNodeDeleted {
			fmt.Printf("a new child node[%s] has beed created\n", e.Path)
		} else if e.Type == zk.EventNodeDataChanged {
			fmt.Printf("child node[%s] has beed changed\n", e.Path)
		} else if e.Type == zk.EventNodeChildrenChanged {
			fmt.Println("there is a child node has beed changed")
		}
	}
}
```

**Comment by dennisafa** [comment]
Nothing is wrong with your code - I have the same issue.

**Comment by sakateka** [comment]
@thep0y @dennisafa 
If I understood everything correctly in the code
https://github.com/go-zookeeper/zk/blob/8866d766b48461a9155fbb2222519e98e9aecb46/conn.go#L815-L823
Then `ChildrenW` can receive events `EventNodeDataChanged` (and it looks like a bug https://github.com/go-zookeeper/zk/issues/38), `EventNodeChildrenChanged`, `EventNodeDeleted`, and only for the path passed to `ChildrenW`.
The session events 

And `EventNotWatching` will also be received from
https://github.com/go-zookeeper/zk/blob/8866d766b48461a9155fbb2222519e98e9aecb46/conn.go#L534-L544
