### ISSUE TITLE
Does this client support ssl connection？

### ISSUE THREAD

**Issue by peaka9** [go-zookeeper/zk#64]
Hello，
      As the Apache ZooKeeper support ssl connection, I want to know whether this go client support ssl connectiong.

**Comment by pmazzini** [comment]
It does. You can use [WithDialer](https://github.com/go-zookeeper/zk/blob/master/conn.go#L233) to pass the ssl dial function.

**Comment by peaka9** [comment]
> It does. You can use [WithDialer](https://github.com/go-zookeeper/zk/blob/master/conn.go#L233) to pass the ssl dial function.

Thank you.
