### ISSUE TITLE
Add contribution guide. 

### ISSUE THREAD

**Issue by jeffbean** [go-zookeeper/zk#8]
The core library should have a guide for contributions

- all changes come with unit/integration tests.
- no external libraries (keep it as it is with no dependencies.) 
- at least one peer review 
- maybe some code coverage checks
- Go style guide (lightly extend the standard library guide)

**Comment by pmazzini** [comment]
Shall we close this one?

**Comment by pmazzini** [comment]
Thanks for adding the contribution guide!
